declare module 'landingApp/landingAppIndex'
declare module 'clientLoginApp/clientLoginAppIndex'
declare module 'enterpriseLoginApp/enterpriseLoginAppIndex'
declare module 'internetBankingMenuApp/internetBankingMenuAppIndex'
declare module 'clientDashboardApp/clientDashboardAppIndex'
declare module 'enterpriseDashboardApp/enterpriseDashboardAppIndex'
declare module 'aboutUsApp/aboutUsAppIndex'
declare module 'productsApp/productsApp'